// ============================================================
// 文件：SchemaManager.cs
// 描述：轻量级数据库 schema 管理 — 替代 SqlSugar CodeFirst
// 功能：使用内嵌 DDL 实现跨数据库的自动建表 + 索引，零额外依赖
// 修改日期：2026-06-03
// ============================================================

using System;
using System.Data;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Dapper;

namespace ZL.ProtocolGateway
{
    /// <summary>
    /// 轻量级数据库 schema 管理 — 替代 SqlSugar CodeFirst。
    /// 使用内嵌 DDL 实现跨数据库的自动建表和索引，零额外依赖。
    /// </summary>
    public static class SchemaManager
    {
        /// <summary>
        /// 数据库提供商枚举
        /// </summary>
        public enum DatabaseProvider
        {
            Sqlite,
            MySql,
            SqlServer,
            PostgreSQL
        }

        // 编译好的正则表达式 — 避免每次调用都重新编译，7×24 生产环境必须做
        private static readonly Regex ValidTableNameRegex = new(
            @"^[a-zA-Z_][a-zA-Z0-9_.]*$",
            RegexOptions.Compiled,
            TimeSpan.FromSeconds(1));

        /// <summary>
        /// 确保目标表和索引存在。若不存在则创建。
        /// </summary>
        /// <param name="connection">已打开的数据库连接</param>
        /// <param name="provider">数据库类型</param>
        /// <param name="tableName">表名（需通过 ValidateTableName 校验）</param>
        /// <param name="ct">取消令牌 — 防止数据库无响应时启动挂死</param>
        public static async Task EnsureTableAsync(IDbConnection connection, DatabaseProvider provider, string tableName, CancellationToken ct = default)
        {
            ValidateTableName(tableName);
            var exists = await IsTableExistsAsync(connection, provider, tableName, ct);
            if (exists) return;

            var sql = GenerateCreateTableSql(provider, tableName);
            // Dapper 2.1.35 ExecuteAsync 无 CancellationToken 参数，依赖默认 command timeout。
            // (IDbConnection) 强转用于隐藏 .NET 8 DbConnection.ExecuteAsync 实例方法。
            await ((IDbConnection)connection).ExecuteAsync(sql);

            // 创建索引以提升查询性能（7×24 运行场景下，无索引的表会无限增长且查询越来越慢）
            await EnsureIndexesAsync(connection, provider, tableName);
        }

        private static async Task<bool> IsTableExistsAsync(IDbConnection connection, DatabaseProvider provider, string tableName, CancellationToken ct)
        {
            string sql = provider switch
            {
                DatabaseProvider.Sqlite => "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=@TableName",
                DatabaseProvider.MySql => "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=@TableName",
                DatabaseProvider.SqlServer => "SELECT COUNT(*) FROM information_schema.tables WHERE table_type='BASE TABLE' AND table_name=@TableName",
                DatabaseProvider.PostgreSQL => "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' AND table_name=@TableName",
                _ => throw new NotSupportedException($"Provider {provider} not supported")
            };
            // Dapper 2.1.35 QuerySingleAsync 无 CancellationToken 参数。
            // (IDbConnection) 强转隐藏 .NET 8 DbConnection.ExecuteAsync 实例方法。
            return await ((IDbConnection)connection).QuerySingleAsync<int>(sql, new { TableName = tableName }) > 0;
        }

        /// <summary>
        /// 验证表名合法性，防止 SQL 注入。
        /// 仅允许字母、数字、下划线、点号，且必须以字母或下划线开头。
        /// </summary>
        public static void ValidateTableName(string tableName)
        {
            if (string.IsNullOrWhiteSpace(tableName))
                throw new ArgumentException("Table name cannot be null or empty.", nameof(tableName));

            if (!ValidTableNameRegex.IsMatch(tableName))
                throw new ArgumentException($"Invalid table name: {tableName}", nameof(tableName));
        }

        private static string GenerateCreateTableSql(DatabaseProvider provider, string tableName)
        {
            string idType = provider switch
            {
                DatabaseProvider.Sqlite => "INTEGER PRIMARY KEY AUTOINCREMENT",
                DatabaseProvider.MySql => "BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY",
                DatabaseProvider.SqlServer => "BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY",
                DatabaseProvider.PostgreSQL => "BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                _ => throw new NotSupportedException()
            };

            string textType = provider switch
            {
                DatabaseProvider.Sqlite => "TEXT",
                DatabaseProvider.MySql => "LONGTEXT",
                DatabaseProvider.SqlServer => "NVARCHAR(MAX)",
                DatabaseProvider.PostgreSQL => "TEXT",
                _ => throw new NotSupportedException()
            };

            string varchar512 = provider switch
            {
                DatabaseProvider.Sqlite => "TEXT",
                DatabaseProvider.MySql => "VARCHAR(512)",
                DatabaseProvider.SqlServer => "NVARCHAR(512)",
                DatabaseProvider.PostgreSQL => "VARCHAR(512)",
                _ => throw new NotSupportedException()
            };

            string varchar64 = provider switch
            {
                DatabaseProvider.Sqlite => "TEXT",
                DatabaseProvider.MySql => "VARCHAR(64)",
                DatabaseProvider.SqlServer => "NVARCHAR(64)",
                DatabaseProvider.PostgreSQL => "VARCHAR(64)",
                _ => throw new NotSupportedException()
            };

            string datetimeType = provider switch
            {
                DatabaseProvider.Sqlite => "TEXT",
                DatabaseProvider.MySql => "DATETIME",
                DatabaseProvider.SqlServer => "DATETIME2",
                DatabaseProvider.PostgreSQL => "TIMESTAMP",
                _ => throw new NotSupportedException()
            };

            string datetimeDefault = provider switch
            {
                DatabaseProvider.Sqlite => "DEFAULT (CURRENT_TIMESTAMP)",
                DatabaseProvider.MySql => "DEFAULT CURRENT_TIMESTAMP",
                DatabaseProvider.SqlServer => "DEFAULT GETUTCDATE()",
                DatabaseProvider.PostgreSQL => "DEFAULT CURRENT_TIMESTAMP",
                _ => throw new NotSupportedException()
            };

            return $@"CREATE TABLE {tableName} (
    Id {idType},
    Topic {varchar512},
    ContentType {varchar64},
    PayloadText {textType},
    PayloadHex {textType},
    MetadataJson {textType},
    CreatedAt {datetimeType} NOT NULL {datetimeDefault}
)";
        }

        /// <summary>
        /// 确保目标索引存在。若不存在则创建。
        /// SQLite 不支持 IF NOT EXISTS，需在执行前检查；MySQL 8+/PostgreSQL/SQL Server 使用 IF NOT EXISTS 安全幂等。
        /// </summary>
        private static async Task EnsureIndexesAsync(IDbConnection connection, DatabaseProvider provider, string tableName)
        {
            string idx1Name = $"idx_{tableName}_CreatedAt";
            string idx2Name = $"idx_{tableName}_Topic";

            if (provider == DatabaseProvider.Sqlite)
            {
                // SQLite 不支持 CREATE INDEX IF NOT EXISTS，需先查询已有索引
                var existing = await ((IDbConnection)connection).QueryAsync<string>(
                    "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name=@Table",
                    new { Table = tableName });
                var existingSet = new HashSet<string>(existing);

                if (!existingSet.Contains(idx1Name))
                {
                    await ((IDbConnection)connection).ExecuteAsync($"CREATE INDEX {idx1Name} ON {tableName} (CreatedAt)");
                }
                if (!existingSet.Contains(idx2Name))
                {
                    await ((IDbConnection)connection).ExecuteAsync($"CREATE INDEX {idx2Name} ON {tableName} (Topic)");
                }
            }
            else
            {
                string ifNotExists = provider switch
                {
                    DatabaseProvider.MySql => "IF NOT EXISTS ",
                    DatabaseProvider.SqlServer => "IF NOT EXISTS ",
                    DatabaseProvider.PostgreSQL => "IF NOT EXISTS ",
                    _ => ""
                };

                await ((IDbConnection)connection).ExecuteAsync($"CREATE {ifNotExists}INDEX {idx1Name} ON {tableName} (CreatedAt)");
                await ((IDbConnection)connection).ExecuteAsync($"CREATE {ifNotExists}INDEX {idx2Name} ON {tableName} (Topic)");
            }
        }

        /// <summary>
        /// 清理过期数据 — 防止数据库无限增长导致磁盘耗尽。
        /// <para>双重策略：时间轮转（删除超过 retentionHours 的行）+ 容量控制（超过 maxRows 时删除最旧批次）。</para>
        /// <para>7×24 运行场景下，无清理的表会在 30 天内增长到数 GB。</para>
        /// </summary>
        /// <param name="connection">已打开的数据库连接</param>
        /// <param name="provider">数据库类型</param>
        /// <param name="tableName">表名（需通过 ValidateTableName 校验）</param>
        /// <param name="retentionHours">保留小时数，0 或负数表示禁用时间轮转（默认 168 = 7 天）</param>
        /// <param name="maxRows">最大行数，0 或负数表示禁用容量控制（默认 1000000）</param>
        /// <returns>删除的总行数</returns>
        public static async Task<int> PurgeOldRowsAsync(IDbConnection connection, DatabaseProvider provider, string tableName, int retentionHours = 168, long maxRows = 1_000_000)
        {
            ValidateTableName(tableName);
            int totalDeleted = 0;

            // 策略 1：时间轮转 — 删除超过 retentionHours 的行
            if (retentionHours > 0)
            {
                string timePurgeSql = provider switch
                {
                    DatabaseProvider.Sqlite => $"DELETE FROM {tableName} WHERE CreatedAt < datetime('now', '-' || @Hours || ' hours')",
                    DatabaseProvider.MySql => $"DELETE FROM {tableName} WHERE CreatedAt < DATE_SUB(NOW(), INTERVAL @Hours HOUR)",
                    DatabaseProvider.SqlServer => $"DELETE FROM {tableName} WHERE CreatedAt < DATEADD(HOUR, -@Hours, GETUTCDATE())",
                    DatabaseProvider.PostgreSQL => $"DELETE FROM {tableName} WHERE CreatedAt < NOW() - INTERVAL '@Hours hours'",
                    _ => throw new NotSupportedException($"Provider {provider} not supported")
                };
                // (IDbConnection) 强转隐藏 .NET 8 DbConnection.ExecuteAsync 实例方法。
                totalDeleted += await ((IDbConnection)connection).ExecuteAsync(timePurgeSql, new { Hours = retentionHours });
            }

            // 策略 2：容量控制 — 超过 maxRows 时删除最旧的批次（每次删除超出部分的 20%）
            if (maxRows > 0)
            {
                string countSql = $"SELECT COUNT(*) FROM {tableName}";
                long currentCount = await ((IDbConnection)connection).QuerySingleAsync<long>(countSql);

                if (currentCount > maxRows)
                {
                    long excessCount = currentCount - maxRows;
                    // 每次删除超出部分的 20%，避免单次大 DELETE 锁表过久
                    long deleteBatch = Math.Max(1000, excessCount / 5);

                    string capacityPurgeSql = provider switch
                    {
                        DatabaseProvider.Sqlite => $"DELETE FROM {tableName} WHERE Id IN (SELECT Id FROM {tableName} ORDER BY CreatedAt ASC LIMIT @Batch)",
                        DatabaseProvider.MySql => $"DELETE FROM {tableName} ORDER BY CreatedAt ASC LIMIT @Batch",
                        DatabaseProvider.SqlServer =>
                            $"WITHToDelete AS (SELECT TOP(@Batch) Id FROM {tableName} ORDER BY CreatedAt ASC) " +
                            $"DELETE FROM {tableName} WHERE Id IN (SELECT Id FROM ToDelete)",
                        DatabaseProvider.PostgreSQL => $"DELETE FROM {tableName} WHERE Id IN (SELECT Id FROM {tableName} ORDER BY CreatedAt ASC LIMIT @Batch)",
                        _ => throw new NotSupportedException($"Provider {provider} not supported")
                    };
                    totalDeleted += await ((IDbConnection)connection).ExecuteAsync(capacityPurgeSql, new { Batch = deleteBatch });
                }
            }

            return totalDeleted;
        }
    }
}
